# Generated by Django 2.0.7 on 2019-03-05 20:19

import apps.consumibles.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'colores',
            },
        ),
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16)),
                ('codigo_proveedor', models.CharField(blank=True, max_length=64)),
                ('cantidad_existente', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, max_length=256, verbose_name='Notaciones')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumibles.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo_movimiento', models.IntegerField(choices=[(0, 'ingreso'), (1, 'salida')], default=1)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[apps.consumibles.validators.noEqual0])),
                ('id_solicitud', models.BigIntegerField(blank=True, choices=[('ALMACEN COLEGIO ALEMAN', ((8006057352, '#INC-3289: Factin'),)), ('Carolina Pinzon', ((8006139579, '#INC-3324: préstamo computador '),)), ('Chukuwata', ((8006018136, '#INC-3237: código 2133'),)), ('IVETH GUTIERREZ', ((8006079301, '#INC-3307: Tutoria docentes kindergarten'),)), ('Inge Buchholz', ((8006013459, '#INC-3230: impresora c21'),)), ('Inna Schoenfeld', ((8006053358, '#INC-3277: Acceso softcafeteria'),)), ('JANETH MANTILLA', ((8006081887, '#INC-3312: RV: Ausencia día miércoles 27 febrero '),)), ('LUIS CARLOS ACERO RONDERO', ((8006099705, '#INC-3322: sala informática c12'), (8006099471, '#INC-3320: sala de indagación TV interactiva liga Master'), (8006062110, '#INC-3297: adicionar a lista Blanca el siguiente u r l'), (8006059899, '#INC-3292: antena wi-fi para c11 y c12'), (8006059879, '#INC-3291: equipo número 2 salón c11'))), ('MARIA EUGENIA ROMAN', ((8006014740, '#INC-3233: página web bloqueada'),)), ('Mary de Castro', ((8006081548, '#INC-3311: Cambio tinta de la impresora'),)), ('Michael Schmid', ((8006078627, '#INC-3304: ctrl-Button at keyboard does not work at C12-03'), (8005983574, '#INC-3210: logout office.com not possible at C12-21'))), ('Monica Clausen', ((8006012419, '#INC-3224: Schoolpack'),)), ('Natalia Schütt', ((8006074236, '#INC-3300: Acceso a Internet'),)), ('Paula Andrea  Royero Padilla', ((8006035845, '#INC-3254: Caida del internet en la sala multimedia'),)), ('SANDRA MARTINEZ', ((8006056868, '#INC-3287: CONFIGURACION DCTOS'), (8006032409, '#INC-3246: INCONVENIENTES NOMINA'), (8006012143, '#INC-3222: CONFIGURACION CONCEPTOS CARTERA'), (8005982656, '#INC-3209: CERTIFICADOS INGRESOS y RET'))), ('SUAT CABALLERO', ((8006036060, '#INC-3256: PROBLEMAS CONSECUTIVOS CAUSACION'), (8006012091, '#INC-3221: FACTIN NO PERMITE REALIZAR OPERACIONES')))], null=True, verbose_name='ticket en freshservice')),
                ('descripcion', models.TextField(blank=True, max_length=256)),
                ('consumible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumibles.Consumible')),
                ('impresora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.Impresora')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.AddField(
            model_name='consumible',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumibles.Proveedor'),
        ),
    ]
