# Generated by Django 2.0.7 on 2018-10-16 05:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16)),
                ('descripcion', models.CharField(blank=True, max_length=256)),
                ('cantidad_existente', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumibles.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo_movimiento', models.IntegerField(choices=[(0, 'ingreso'), (1, 'salida'), (2, 'cuadre')], default=1)),
                ('cantidad', models.IntegerField(default=1)),
                ('descripcion', models.CharField(blank=True, max_length=256)),
                ('consumible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumibles.Consumible')),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Impresora')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=128)),
                ('numero_ticket', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumibles.Solicitud'),
        ),
        migrations.AddField(
            model_name='consumible',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumibles.Proveedor'),
        ),
    ]
