# Generated by Django 2.0.7 on 2018-10-31 12:32

import apps.consumibles.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'colores',
            },
        ),
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16)),
                ('cantidad_existente', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, max_length=256, verbose_name='Notaciones')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumibles.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo_movimiento', models.IntegerField(choices=[(0, 'ingreso'), (1, 'salida')], default=1)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[apps.consumibles.validators.noEqual0])),
                ('id_solicitud', models.BigIntegerField(choices=[('ABRAHANN GATTAS OBEID', ((8004007568, '#INC-1612: RV: Journal Entries 2018: Solicitud de descarga de data - CORPORACIÓN CULTURAL COLEGIO ALEMAN '),)), ('ALCIRA MARTINEZ', ((8003983668, '#INC-1579: SOFTWARE TRACKER'),)), ('CLAUDIA URUETA', ((8004091431, '#INC-1694: Ingreso portatil'), (8004020911, '#INC-1621: SOLICITUD COMPUTADOR'))), ('Carolina Morales', ((8003615514, '#INC-1282: Revision tablero computador proyector  y sonido salon b33'),)), ('GLORIA NAVARRO', ((8004064144, '#INC-1670: Eventual traslado de portátil'),)), ('Gisele Pajaro Fajardo', ((8004043229, '#INC-1647: Inconvenientes PC y Onedrive- Gisele Pájaro '),)), ('HEIDY NAVARRO', ((8004066709, '#INC-1677: Regreso de impresora'),)), ('IVETH GUTIERREZ', ((8004111705, '#INC-1723: Video Camara'),)), ('JOSIMAR CERVANTES', ((8004113136, '#INC-1726: Apoyo salón múltiple'),)), ('Juan Maradey', ((8004126961, '#INC-1752: Instalación java en c11'), (8003999689, '#INC-1589: Instalación de programas en PC de C15'))), ('Julie Huet', ((8003748778, '#INC-1395: Problema linea telefonica'),)), ('KATHARINA RENZ', ((8004123890, '#INC-1744: Proyección pantalla salón C13'),)), ('Kai Busemeyer', ((8004061196, '#INC-1665: ordenador defectuoso'),)), ('Kelly Almanza', ((8003710072, '#INC-1362: cierre punto ap primaria primer piso'),)), ('LUCIA ROBLES', ((8004041235, '#INC-1642: Urgente: revisar acceso a TYPO 3'),)), ('LUIS FERNANDO LOPEZ', ((8004096894, '#INC-1707: señal cable hdmi intermitente del TV'),)), ('Laura Puerta', ((8004047026, '#INC-1655: Gasto del toner de impresora oficina de psicología'),)), ('MONICA PAEZ', ((8003509850, '#INC-1169: Calibración tablero + Starboard'),)), ('Marius Steies', ((8003798688, '#INC-1456: cambio de computadores'),)), ('Michael Schmid', ((8004066100, '#INC-1675: Improvement of digital Workflow at teachers room'), (8003950030, '#INC-1557: Problemas con el computadors en el computador c12'))), ('OLGA SANJUAN', ((8004127058, '#INC-1753: reubicación del portátil'),)), ('Paula Andrea Royero Padilla', ((8004096082, '#INC-1705: Computador N° 2 sin Internet'),)), ('Salón Tecnología C12', ((8004125268, '#INC-1749: Visita Legamaster Biblioteca parea visita Rectores '),)), ('janina oechsle', ((8004047635, '#INC-1657: RV: Portátil sin conexión al internet '),)), ('luz angela  toro padilla', ((8004123479, '#INC-1743: colocar toner'),))], verbose_name='id de ticket en freshservice')),
                ('descripcion', models.TextField(blank=True, max_length=256)),
                ('consumible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumibles.Consumible')),
                ('impresora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.Impresora')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.AddField(
            model_name='consumible',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumibles.Proveedor'),
        ),
    ]
