# Generated by Django 2.0.7 on 2018-10-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumibles', '0002_auto_20181020_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id_solicitud',
            field=models.BigIntegerField(choices=[('Requester', ((1, '#INC-1: Sample Ticket'),))], verbose_name='id de ticket en freshservice'),
        ),
    ]
