# Generated by Django 2.0.7 on 2018-10-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumibles', '0003_auto_20181020_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='id_solicitud',
            field=models.IntegerField(choices=[('CLAUDIA URUETA', ((8003882943, '#INC-1473: ESTUDIANTES NUEVOS'),)), ('Carolina Morales', ((8003615514, '#INC-1282: Revision tablero computador proyector  y sonido salon b33'),)), ('DAYANA MARQUEZ', ((8003413072, '#INC-1079: necesidad de  2 video beam '),)), ('Elvia Guzman', ((8003386769, '#INC-1044: reporte notas SP'),)), ('Erika Buitrago', ((8003388861, '#INC-1047: Revisión del cableado de todos los equipos de computo.'),)), ('HEIDY FANDINO', ((8003925156, '#INC-1527: Grabaciones IB'),)), ('HEIDY NAVARRO', ((8003950371, '#INC-1562: Impresora sala múltiple'),)), ('JOHANA MARQUEZ', ((8003936572, '#INC-1546: No hay internet '),)), ('Julie Huet', ((8003748778, '#INC-1395: Problema linea telefonica'),)), ('Junell Araujo', ((8003776945, '#INC-1426: Revisar computador del atelier'),)), ('Karen Grunwaldt', ((8003752431, '#INC-1401: SCHOOL PACK'),)), ('Karla Ballesteros', ((8003945311, '#INC-1552: Parvulario 2'),)), ('Kelly Almanza', ((8003710072, '#INC-1362: cierre punto ap primaria primer piso'),)), ('LIZBANA RUEDA VILLANOVA', ((8003936727, '#INC-1547: Capacitación monografía en ciencias'),)), ('LUCIA ROBLES', ((8003402703, '#INC-1065: Errores página web alemán'),)), ('LUIS CARLOS ACERO RONDERO', ((8003675779, '#INC-1337: Actualización de teamspeak'),)), ('LUIS FERNANDO LOPEZ', ((8003498082, '#INC-1161: revisión mancha tv'), (8003403813, '#INC-1069: favor devolver sistema de sonido'))), ('Libardo Castro Peña', ((8003478773, '#INC-1143: Revisión video beam salón B32'),)), ('MONICA PAEZ', ((8003891852, '#INC-1497: Starboard + mosue'), (8003509850, '#INC-1169: Calibración tablero + Starboard'))), ('Marius Steies', ((8003798688, '#INC-1456: cambio de computadores'),)), ('Michael Schmid', ((8003950030, '#INC-1557: Problemas con el computadors en el computador c12'), (8003726904, '#INC-1382: vídeoproyector en el Salón'), (8003651166, '#INC-1313:  Ersatz defekter Hardware/Sustitución de hardware defectuoso'))), ('Paula Andrea Royero Padilla', ((8003886606, '#INC-1482: Caida del sistema de Biblioteca'),)), ('Recepcion Colegio Alemán', ((8003620913, '#INC-1287: PROBLEMA SOFT CAFETERIA'),)), ('Rocio de la Hoz', ((8003498143, '#INC-1164: Bateria portatil '),)), ('SILVANA FONNEGRA', ((8003945206, '#INC-1551: internet para celulares y computador'), (8003903982, '#INC-1502: Computador no arranca')))], verbose_name='id de ticket en freshservice'),
        ),
    ]
