# Generated by Django 2.0.7 on 2018-10-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumibles', '0004_auto_20181020_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumible',
            name='descripcion',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
