# Generated by Django 2.0.7 on 2018-10-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumibles', '0005_auto_20181021_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumible',
            name='cantidad_existente',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumible',
            name='descripcion',
            field=models.TextField(blank=True, max_length=256, verbose_name='Notaciones'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id_solicitud',
            field=models.BigIntegerField(choices=[('ALCIRA MARTINEZ', ((8003983668, '#INC-1579: SOFTWARE TRACKER'),)), ('CARMEN ANDRADE', ((8003986281, '#INC-1585: Restaurar acceso a los recursos de mi área de Individuos y Sociedades'),)), ('CLAUDIA URUETA', ((8003882943, '#INC-1473: ESTUDIANTES NUEVOS'),)), ('Carolina Morales', ((8003615514, '#INC-1282: Revision tablero computador proyector  y sonido salon b33'),)), ('EDWIN ORTIZ', ((8003365848, '#INC-1015: Reemplazar tonner Impresora P2035n'),)), ('Elvia Guzman', ((8003386769, '#INC-1044: reporte notas SP'), (8003334473, '#INC-985: Notas Alemán y resultados encuesta'))), ('Gisele Pajaro Fajardo', ((8003374952, '#INC-1030: Banners secciones Página Web'), (8003303226, '#INC-950: Solicitud - Dar de baja página vieja'))), ('HEIDY FANDINO', ((8003925156, '#INC-1527: Grabaciones IB'),)), ('IVETH GUTIERREZ', ((8003254088, '#INC-883: Computador de Atelier está lento '),)), ('JOHANA MARQUEZ', ((8003936572, '#INC-1546: No hay internet '),)), ('Julie Huet', ((8003748778, '#INC-1395: Problema linea telefonica'),)), ('Kelly Almanza', ((8003710072, '#INC-1362: cierre punto ap primaria primer piso'),)), ('LIZBANA RUEDA VILLANOVA', ((8003936727, '#INC-1547: Capacitación monografía en ciencias'),)), ('LUCIA ROBLES', ((8003402703, '#INC-1065: Errores página web alemán'),)), ('LUIS CARLOS ACERO RONDERO', ((8003675779, '#INC-1337: Actualización de teamspeak'),)), ('LUIS FERNANDO LOPEZ', ((8003498082, '#INC-1161: revisión mancha tv'), (8003403813, '#INC-1069: favor devolver sistema de sonido'))), ('Libardo Castro Peña', ((8003478773, '#INC-1143: Revisión video beam salón B32'),)), ('MONICA PAEZ', ((8003891852, '#INC-1497: Starboard + mosue'), (8003509850, '#INC-1169: Calibración tablero + Starboard'))), ('Marius Steies', ((8003798688, '#INC-1456: cambio de computadores'),)), ('Michael Schmid', ((8003950030, '#INC-1557: Problemas con el computadors en el computador c12'), (8003726904, '#INC-1382: vídeoproyector en el Salón'), (8003651166, '#INC-1313:  Ersatz defekter Hardware/Sustitución de hardware defectuoso'))), ('Paula Andrea Royero Padilla', ((8003886606, '#INC-1482: Caida del sistema de Biblioteca'),)), ('Recepcion Colegio Alemán', ((8003620913, '#INC-1287: PROBLEMA SOFT CAFETERIA'),)), ('Rocio de la Hoz', ((8003498143, '#INC-1164: Bateria portatil '),)), ('SILVANA FONNEGRA', ((8003903982, '#INC-1502: Computador no arranca'),))], verbose_name='id de ticket en freshservice'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.IntegerField(choices=[(0, 'ingreso'), (1, 'salida'), (2, 'ingreso de cuadre'), (3, 'salida de cuadre')], default=1),
        ),
    ]
