# Generated by Django 2.0.7 on 2018-10-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20181021_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Departamento'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='impresora',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventario.Impresora'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Ubicacion'),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='estado',
            field=models.IntegerField(choices=[(0, 'En Stock'), (1, 'Operativa'), (2, 'Averiada')], default=0),
        ),
    ]
