# Generated by Django 2.0.7 on 2018-10-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20181021_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'verbose_name_plural': 'asignaciones'},
        ),
        migrations.AlterModelOptions(
            name='fabricanteimpresora',
            options={'verbose_name_plural': 'fabricantes de impresora'},
        ),
        migrations.AlterModelOptions(
            name='modeloimpresora',
            options={'verbose_name_plural': 'modelos de impresora'},
        ),
        migrations.AlterModelOptions(
            name='tipoimpresion',
            options={'verbose_name_plural': 'tipo de impresiones'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name_plural': 'ubicaciones'},
        ),
    ]
