# Generated by Django 2.0.7 on 2018-10-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20181021_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloimpresora',
            name='funcionalidad',
            field=models.BooleanField(default=True, verbose_name='es multi-funcional'),
        ),
        migrations.AlterField(
            model_name='modeloimpresora',
            name='conexion_local',
            field=models.BooleanField(default=True, verbose_name='tiene conexion USB'),
        ),
        migrations.AlterField(
            model_name='modeloimpresora',
            name='conexion_red_cableada',
            field=models.BooleanField(default=False, verbose_name='tiene conexion LAN'),
        ),
        migrations.AlterField(
            model_name='modeloimpresora',
            name='conexion_red_inalambrica',
            field=models.BooleanField(default=False, verbose_name='tiene conexion WiFi'),
        ),
        migrations.AlterField(
            model_name='modeloimpresora',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.TipoImpresion', verbose_name='tipo impresion'),
        ),
    ]
